### ISSUE TITLE
Bug: Perf regression on 3.1.1

### ISSUE THREAD

**Issue by r0kan** [azat-io/eslint-plugin-perfectionist#195] opened 2024-08-05 08:03 UTC
### Describe the bug

Hi. After upgrading from version 3.0 to version 3.1, the linting process has significantly increased in duration.

3.0.0
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
prettier/prettier                                         |   373.605 |    52.7%
@typescript-eslint/no-unsafe-argument                     |    74.473 |    10.5%
@typescript-eslint/no-unsafe-assignment                   |    67.121 |     9.5%
@typescript-eslint/no-unsafe-return                       |    18.050 |     2.5%
@typescript-eslint/no-unused-vars                         |    17.855 |     2.5%
react/no-direct-mutation-state                            |    15.891 |     2.2%
@typescript-eslint/no-unsafe-member-access                |     9.214 |     1.3%
import/no-extraneous-dependencies                         |     8.834 |     1.2%
import/no-duplicates                                      |     6.849 |     1.0%
react/require-render-return                               |     5.860 |     0.8%
padding-line-between-statements                           |     4.239 |     0.6%
@typescript-eslint/await-thenable                         |     3.604 |     0.5%
jest/expect-expect                                        |     3.530 |     0.5%
@typescript-eslint/no-unsafe-call                         |     3.480 |     0.5%
@typescript-eslint/no-unnecessary-type-arguments          |     2.937 |     0.4%
@typescript-eslint/no-empty-function                      |     2.732 |     0.4%
perfectionist/sort-switch-case                            |     2.670 |     0.4%
react/no-deprecated                                       |     2.631 |     0.4%
react/jsx-no-target-blank                                 |     2.630 |     0.4%
@typescript-eslint/no-base-to-string                      |     2.574 |     0.4%
perfectionist/sort-objects                                |     2.546 |     0.4%
@typescript-eslint/no-unnecessary-type-parameters         |     2.512 |     0.4%
@typescript-eslint/prefer-promise-reject-errors           |     1.916 |     0.3%
@typescript-eslint/explicit-module-boundary-types         |     1.881 |     0.3%
react/no-string-refs                                      |     1.703 |     0.2%
@typescript-eslint/no-unsafe-enum-comparison              |     1.691 |     0.2%
@typescript-eslint/prefer-string-starts-ends-with         |     1.560 |     0.2%
@typescript-eslint/consistent-type-imports                |     1.547 |     0.2%
perfectionist/sort-classes                                |     1.455 |     0.2%

3.1.1
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
perfectionist/sort-objects              |   610.410 |    25.4%
perfectionist/sort-classes              |   480.044 |    20.0%
prettier/prettier                       |   380.296 |    15.8%
perfectionist/sort-named-imports        |   221.563 |     9.2%
perfectionist/sort-object-types         |   200.118 |     8.3%
perfectionist/sort-union-types          |   102.489 |     4.3%
@typescript-eslint/no-unsafe-assignment |    79.151 |     3.3%
@typescript-eslint/no-unsafe-argument   |    76.752 |     3.2%
perfectionist/sort-named-exports        |    19.182 |     0.8%

### Code example

-

### ESLint version

v8.57.0

### ESLint Plugin Perfectionist version

v3.1.1

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment] 2024-08-05 08:53
This is interesting.

In version 3.1 we upgraded typescript-eslint from v7 to v8 in #186. Perhaps the problem is related to this, there are no other global changes.

I will try to check the difference between versions 3.0 and 3.1.

**Comment by hugop95** [comment] 2024-08-05 14:00
I believe that the performance impact comes from
https://github.com/azat-io/eslint-plugin-perfectionist/commit/8f04df992af59db4a142f6ba95a83af533a75f31

which uses `structuredClone` instead of using the original element.

**Comment by azat-io** [comment] 2024-08-05 14:56
@hugop95 Thank you for your work!

**Comment by azat-io** [comment] 2024-08-05 15:52
Fixed in 00b2cc3c04ffad627b7e8235cd9df0f21a393000. Released in [v3.1.2](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.2)

**Closed by azat-io** 2024-08-05 15:52 UTC
Labels: bug
