### ISSUE TITLE
Feature: The order changes for elements of the same length when new elements are added

### ISSUE THREAD

**Issue by brightsider** [azat-io/eslint-plugin-perfectionist#59] opened 2023-08-25 09:45 UTC
### What rule do you want to change?

sort-imports

### Describe the problem

I've this config:
```
    "perfectionist/sort-imports": [
      "error",
      {
        "type": "line-length",
        "groups": [
          ["builtin", "external", "type", "external-type", "builtin-type", "side-effect"],
          ["internal-type", "internal"],
          ["parent", "parent-type"],
          ["sibling-type", "sibling", "index-type", "index"],
          ["style", "object", "unknown"]
        ],
      ]
```

On every change in the file I've a lot of changes. Would be great if you add additional subrule to keep lines with the same length in the old places.

<img width="653" alt="image" src="https://github.com/azat-io/eslint-plugin-perfectionist/assets/4996231/80bbb8dc-87e0-41e4-af39-92c798f3d1f1">

### Code example

Any imports with the same length

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment] 2023-09-04 22:01
I didn't really get the point of the problem. A large number of changes after a fix is normal. But it's only going to happen once.

**Comment by brightsider** [comment] 2023-09-05 11:00
When we add some changes, imports with the same length are sorted in different ways and we get many conflicts when someone works with the same file. If we had the same rule for the same length, we would have changed only for changed lines, not the whole file.

**Comment by azat-io** [comment] 2023-09-05 12:21
Could you provide me code with your imports?
I am currently unable to reproduce the problem.

**Comment by brightsider** [comment] 2023-09-06 04:38
Create file:
```
export const test = {
  a: 'a',
  b: 'b',
  c: 'c',
  d: 'd1',
};
```
Use lint, nothing changed
Change to this:
```
export const test = {
  a: 'a',
  b: 'b',
  c: 'c',
  e: 'e12',
  d: 'd1',
};
```
Use lint, we have this file now:
```
export const test = {
  c: 'c',
  b: 'b',
  a: 'a',
  d: 'd1',
  e: 'e12',
};
```
Then change to this:
```
export const test = {
  c: 'c',
  b: 'b',
  a: 'a',
  f: 'f123',
  d: 'd1',
  e: 'e12',
};
```
Call lint:
```
export const test = {
  a: 'a',
  b: 'b',
  c: 'c',
  d: 'd1',
  e: 'e12',
  f: 'f123',
};
```

We have different orders of the same length strings when linter do changes - keys a, b, c.

**Comment by azat-io** [comment] 2023-09-06 08:55
Fixed in c0e2e606e449fc392ecfe0ba600b2514f2c6dadf.

Will be released today.

**Comment by azat-io** [comment] 2023-09-06 11:51
Released in [v2.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v2.0.0)

**Comment by brightsider** [comment] 2023-09-07 05:48
Looks broken now:
1
```
import { PetCard } from './pet-card';
import { HeaderWrap } from './header';
import { ReachOut } from './reach-out';
import { TabsPage } from './tabs-page';
import { MenuCard } from './menu-card';
export { BillCard } from './bill-card';
import { IdleTimer } from './idle-timer';
import { FilesList } from './files-list';
import { ChatOption } from './chat-option';
import { ClientList } from './client-list';
import { TaskListCard } from './task-card';
import { ChatHeader } from './chat-header';
import { Walkthrough } from './walkthrough';
import { LoaderRedux } from './loader-redux';
export { AudioPlayer } from './audio-player';
export { ArrivalBadge } from './arrival-badge';
import { ERInfoDialog } from './er-info-dialog';
import { ContactOption } from './contact-option';
import { AudioDropzone } from './audio-dropzone';
export { AnalyticsCard } from './analytics-card';
import { AssignToModal } from './assign-to-modal';
import { OutdatedBanner } from './outdated-banner';
import { OnCallDocInfo } from './on-call-doc-info';
export { VoicemailAudio } from './voicemail-audio';
import { SelectAssignee } from './select-assignee';
```
2
i```
mport { PetCard } from './pet-card';
import { HeaderWrap } from './header';
export { VoicemailAudio } from './voicemail-audio';
import { ReachOut } from './reach-out';
import { TabsPage } from './tabs-page';
import { MenuCard } from './menu-card';
export { BillCard } from './bill-card';
import { IdleTimer } from './idle-timer';
import { FilesList } from './files-list';
import { ChatOption } from './chat-option';
import { ClientList } from './client-list';
import { TaskListCard } from './task-card';
import { ChatHeader } from './chat-header';
import { Walkthrough } from './walkthrough';
import { LoaderRedux } from './loader-redux';
export { AudioPlayer } from './audio-player';
export { ArrivalBadge } from './arrival-badge';
import { ERInfoDialog } from './er-info-dialog';
import { ContactOption } from './contact-option';
import { AudioDropzone } from './audio-dropzone';
export { AnalyticsCard } from './analytics-card';
import { AssignToModal } from './assign-to-modal';
import { OutdatedBanner } from './outdated-banner';
import { OnCallDocInfo } from './on-call-doc-info';
import { SelectAssignee } from './select-assignee';
```
After lint:
```
import { PetCard } from './pet-card';
import { HeaderWrap } from './header';
export { BillCard } from './bill-card';
import { ReachOut } from './reach-out';
import { TabsPage } from './tabs-page';
import { MenuCard } from './menu-card';
export { AudioPlayer } from './audio-player';
import { IdleTimer } from './idle-timer';
import { FilesList } from './files-list';
import { ChatOption } from './chat-option';
import { ClientList } from './client-list';
import { TaskListCard } from './task-card';
import { ChatHeader } from './chat-header';
import { Walkthrough } from './walkthrough';
import { LoaderRedux } from './loader-redux';
export { ArrivalBadge } from './arrival-badge';
export { AnalyticsCard } from './analytics-card';
import { ERInfoDialog } from './er-info-dialog';
import { ContactOption } from './contact-option';
import { AudioDropzone } from './audio-dropzone';
export { VoicemailAudio } from './voicemail-audio';
import { AssignToModal } from './assign-to-modal';
import { OutdatedBanner } from './outdated-banner';
import { OnCallDocInfo } from './on-call-doc-info';
import { SelectAssignee } from './select-assignee';
```

This code moved and then fixed wrongly with lint
`export { AudioPlayer } from './audio-player';`

**Comment by brightsider** [comment] 2023-09-12 05:53
@azat-io take a look please.

**Comment by azat-io** [comment] 2023-09-12 12:28
The problem is that any code between imports is considered a delimiter. In your case, imports mixed with exports will not be sorted automatically.

**Closed by azat-io** 2023-09-12 12:28 UTC
Labels: enhancement
